[package]
name = "litebox_shim_windows"
version = "0.1.0"
edition = "2024"

[dependencies]
int-enum = "1.2.0"
litebox = { path = "../litebox/", version = "0.1.0" }
litebox_common_linux = { path = "../litebox_common_linux/", version = "0.1.0" }
litebox_common_windows = { path = "../litebox_common_windows/", version = "0.1.0" }
litebox_util_log = { path = "../litebox_util_log", version = "0.1.0" }
thiserror = { version = "2.0.6", default-features = false }
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
litebox_platform_linux_userland = { path = "../litebox_platform_linux_userland/", version = "0.1.0" }

[target.'cfg(target_os = "windows")'.dev-dependencies]
litebox_platform_windows_userland = { path = "../litebox_platform_windows_userland/", version = "0.1.0" }

[lints]
workspace = true
