[package]
name = "litebox_common"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/microsoft/litebox"
description = "Common definitions shared across LiteBox shims and platforms"

[dependencies]
spin = { version = "0.9.8", default-features = false, features = ["once"] }

[lints]
workspace = true