[package]
name = "litebox_broker_platform_macos_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
litebox_platform = { path = "../litebox_platform", version = "0.1.0" }

[target.'cfg(target_os = "macos")'.dependencies]
litebox_common_macos = { path = "../litebox_common_macos", version = "0.1.0" }
libc = { version = "0.2.177", default-features = false }

[features]
lock_tracing = ["litebox_platform/lock_tracing"]

[lints]
workspace = true
