[package]
name = "litebox_packager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.33", features = ["derive"] }
litebox_syscall_rewriter = { version = "0.1.0", path = "../litebox_syscall_rewriter" }
rayon = "1.10"
tar = "0.4"

flate2 = "1.1"
oci-spec = { version = "0.9", features = ["image"] }
tempfile = "3"
walkdir = "2.0"

[lints]
workspace = true
