// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

const API_SET_MAPPINGS: &[(&str, &str)] = &[
    ("api-ms-win-core-apiquery-l1-1-0", "ntdll.dll"),
    ("api-ms-win-core-apiquery-l1-1-2", "ntdll.dll"),
    ("api-ms-win-core-apiquery-l2-1-1", "kernelbase.dll"),
    ("api-ms-win-core-appcompat-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-appcompat-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-appinit-l1-1-0", "kernel32.dll"),
    ("api-ms-win-core-atoms-l1-1-0", "kernel32.dll"),
    ("api-ms-win-core-backgroundtask-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-calendar-l1-1-0", "kernel32.dll"),
    ("api-ms-win-core-comm-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-comm-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-commandlinetoargv-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-console-ansi-l2-1-0", "kernel32.dll"),
    ("api-ms-win-core-console-internal-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-console-l1-2-2", "kernelbase.dll"),
    ("api-ms-win-core-console-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l2-2-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l3-1-0", "kernelbase.dll"),
    ("api-ms-win-core-console-l3-2-0", "kernelbase.dll"),
    ("api-ms-win-core-crt-l1-1-0", "ntdll.dll"),
    ("api-ms-win-core-crt-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-datetime-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-datetime-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-datetime-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-debug-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-debug-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-debug-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-delayload-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-delayload-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-downlevel-shlwapi-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-errorhandling-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-errorhandling-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-errorhandling-l1-1-3", "kernelbase.dll"),
    ("api-ms-win-core-fibers-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-fibers-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-fibers-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-fibers-l2-1-1", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-2-2", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-2-3", "kernelbase.dll"),
    ("api-ms-win-core-file-l1-2-5", "kernelbase.dll"),
    ("api-ms-win-core-file-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-file-l2-1-1", "kernelbase.dll"),
    ("api-ms-win-core-file-l2-1-2", "kernelbase.dll"),
    ("api-ms-win-core-file-l2-1-3", "kernelbase.dll"),
    ("api-ms-win-core-file-l2-1-4", "kernelbase.dll"),
    ("api-ms-win-core-handle-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-heap-obsolete-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-heap-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-heap-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-heap-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-interlocked-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-io-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-io-l1-1-1", "kernel32.dll"),
    ("api-ms-win-core-job-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-largeinteger-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l1-2-2", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l1-2-3", "kernelbase.dll"),
    ("api-ms-win-core-libraryloader-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-localization-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-localization-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-localization-l1-2-4", "kernelbase.dll"),
    ("api-ms-win-core-localization-l2-1-0", "kernelbase.dll"),
    (
        "api-ms-win-core-localization-obsolete-l1-2-0",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-localization-private-l1-1-0",
        "kernelbase.dll",
    ),
    ("api-ms-win-core-localregistry-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-memory-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-memory-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-memory-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-memory-l1-1-9", "kernelbase.dll"),
    ("api-ms-win-core-misc-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-namedpipe-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-namedpipe-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-namedpipe-l1-2-2", "kernelbase.dll"),
    ("api-ms-win-core-namespace-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-normalization-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-path-l1-1-0", "kernelbase.dll"),
    (
        "api-ms-win-core-processenvironment-l1-1-0",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-processenvironment-l1-1-1",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-processenvironment-l1-2-0",
        "kernelbase.dll",
    ),
    ("api-ms-win-core-processsnapshot-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-processthreads-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-processthreads-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-processthreads-l1-1-2", "kernelbase.dll"),
    ("api-ms-win-core-processthreads-l1-1-3", "kernelbase.dll"),
    ("api-ms-win-core-processthreads-l1-1-8", "kernel32.dll"),
    ("api-ms-win-core-processtopology-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-profile-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-pcw-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-psapi-ansi-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-psapi-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-realtime-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-registry-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-rtlsupport-l1-1-0", "ntdll.dll"),
    ("api-ms-win-core-rtlsupport-l1-1-1", "ntdll.dll"),
    ("api-ms-win-core-rtlsupport-l1-2-2", "ntdll.dll"),
    ("api-ms-win-core-sidebyside-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-string-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-string-l2-1-1", "kernelbase.dll"),
    ("api-ms-win-core-synch-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-synch-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-synch-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-synch-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-2-1", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-2-3", "kernelbase.dll"),
    ("api-ms-win-core-sysinfo-l1-2-8", "kernelbase.dll"),
    ("api-ms-win-core-systemtopology-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-systemtopology-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-threadpool-legacy-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-threadpool-l1-2-0", "kernelbase.dll"),
    (
        "api-ms-win-core-threadpool-private-l1-1-0",
        "kernelbase.dll",
    ),
    ("api-ms-win-core-timezone-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-util-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-version-l1-1-1", "kernelbase.dll"),
    (
        "api-ms-win-core-windowserrorreporting-l1-1-0",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-windowserrorreporting-l1-1-1",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-windowserrorreporting-l1-1-2",
        "kernelbase.dll",
    ),
    (
        "api-ms-win-core-windowserrorreporting-l1-1-3",
        "kernelbase.dll",
    ),
    ("api-ms-win-core-wow64-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-wow64-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-wow64-l1-1-3", "kernelbase.dll"),
    ("api-ms-win-core-xstate-l2-1-0", "kernelbase.dll"),
    ("api-ms-win-core-xstate-l2-1-1", "kernelbase.dll"),
    ("api-ms-win-core-xstate-l2-1-2", "kernelbase.dll"),
    ("api-ms-win-eventing-consumer-l1-1-0", "sechost.dll"),
    ("api-ms-win-eventing-consumer-l1-1-1", "sechost.dll"),
    ("api-ms-win-eventing-controller-l1-1-0", "sechost.dll"),
    ("api-ms-win-eventing-provider-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-security-audit-l1-1-0", "sechost.dll"),
    ("api-ms-win-security-audit-l1-1-1", "sechost.dll"),
    ("api-ms-win-security-appcontainer-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-security-base-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-security-base-l1-2-0", "kernelbase.dll"),
    ("api-ms-win-security-base-private-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-security-lsalookup-l1-1-0", "sechost.dll"),
    ("api-ms-win-security-sddl-l1-1-0", "sechost.dll"),
    ("api-ms-win-service-core-l1-1-0", "sechost.dll"),
    ("api-ms-win-service-core-l1-1-1", "sechost.dll"),
    ("api-ms-win-service-core-l1-1-2", "sechost.dll"),
    ("api-ms-win-service-management-l1-1-0", "sechost.dll"),
    ("api-ms-win-service-management-l2-1-0", "sechost.dll"),
    ("api-ms-win-service-private-l1-1-0", "sechost.dll"),
    ("api-ms-win-service-private-l1-1-2", "sechost.dll"),
    ("api-ms-win-service-private-l1-1-3", "sechost.dll"),
    ("api-ms-win-service-winsvc-l1-1-0", "sechost.dll"),
    ("api-ms-win-core-interlocked-l1-2-0", "kernelbase.dll"),
    (
        "api-ms-win-core-kernel32-legacy-ansi-l1-1-0",
        "kernel32.dll",
    ),
    ("api-ms-win-core-kernel32-legacy-l1-1-6", "kernel32.dll"),
    ("api-ms-win-core-kernel32-private-l1-1-2", "kernel32.dll"),
    ("api-ms-win-core-kernel32-private-l1-2-0", "kernel32.dll"),
    ("api-ms-win-core-localization-ansi-l1-1-0", "kernel32.dll"),
    ("api-ms-win-core-privateprofile-l1-1-1", "kernel32.dll"),
    (
        "api-ms-win-core-processenvironment-ansi-l1-1-0",
        "kernel32.dll",
    ),
    ("api-ms-win-core-psm-key-l1-1-3", "kernelbase.dll"),
    ("api-ms-win-core-quirks-l1-1-1", "kernelbase.dll"),
    ("api-ms-win-core-registry-l2-1-0", "advapi32.dll"),
    ("api-ms-win-core-registry-l2-2-0", "advapi32.dll"),
    ("api-ms-win-core-registry-l2-3-0", "advapi32.dll"),
    ("api-ms-win-core-shlwapi-legacy-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-core-string-obsolete-l1-1-1", "kernel32.dll"),
    ("api-ms-win-core-stringansi-l1-1-0", "kernelbase.dll"),
    ("api-ms-win-crt-locale-l1-1-0", "ucrtbase.dll"),
    ("api-ms-win-crt-math-l1-1-0", "ucrtbase.dll"),
    ("api-ms-win-crt-private-l1-1-0", "ucrtbase.dll"),
    ("api-ms-win-crt-runtime-l1-1-0", "ucrtbase.dll"),
    ("api-ms-win-crt-string-l1-1-0", "ucrtbase.dll"),
    (
        "api-ms-win-eventing-classicprovider-l1-1-0",
        "kernelbase.dll",
    ),
    ("api-ms-win-gdi-internal-uap-l1-1-0", "gdi32full.dll"),
    ("api-ms-win-service-private-l1-2-2", "sechost.dll"),
    (
        "api-ms-win-stateseparation-helpers-l1-1-1",
        "kernelbase.dll",
    ),
    ("ext-ms-win-appcompat-apphelp-l1-1-2", "apphelp.dll"),
    ("ext-ms-win-authz-context-l1-1-0", "authz.dll"),
    ("ext-ms-win-core-winrt-remote-l1-1-0", ""),
    ("ext-ms-win-oobe-query-l1-1-0", ""),
    (
        "ext-ms-win-packagevirtualizationcontext-l1-1-0",
        "daxexec.dll",
    ),
    ("ext-ms-win-rpc-ssl-l1-1-0", "rpcrtremote.dll"),
];
