[package]
name = "litebox_broker_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
litebox_broker_core = { path = "../litebox_broker_core", version = "0.1.0" }
litebox_broker_server = { path = "../litebox_broker_server", version = "0.1.0" }
litebox_broker_unix_socket = { path = "../litebox_broker_unix_socket", version = "0.1.0" }

[[bin]]
name = "litebox-broker-userland"
path = "src/main.rs"

[dev-dependencies]
litebox_broker_client = { path = "../litebox_broker_client", version = "0.1.0" }
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }

[lints]
workspace = true
