[package]
name = "litebox_broker_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.33", features = ["derive"] }
litebox_broker_core = { path = "../litebox_broker_core", version = "0.1.0" }
litebox_broker_host = { path = "../litebox_broker_host", version = "0.1.0" }
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }
litebox_broker_transport = { path = "../litebox_broker_transport", version = "0.1.0", features = ["linux-userland"] }
tempfile = { version = "3", default-features = false }

[[bin]]
name = "litebox-broker-userland"
path = "src/main.rs"

[[test]]
name = "userland_broker"
path = "tests/userland_broker.rs"
harness = false

[dev-dependencies]
litebox_broker_local = { path = "../litebox_broker_local", version = "0.1.0" }

[lints]
workspace = true
