[package]
name = "litebox_broker_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.33", features = ["derive"] }
getrandom = { version = "0.3.4", default-features = false }
litebox_broker_core = { path = "../litebox_broker_core", version = "0.1.0" }
litebox_broker_host = { path = "../litebox_broker_host", version = "0.1.0" }
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }
litebox_broker_transport = { path = "../litebox_broker_transport", version = "0.1.0" }
litebox_platform = { path = "../litebox_platform", version = "0.1.0" }

[target.'cfg(target_os = "linux")'.dependencies]
litebox_broker_platform_linux_userland = { path = "../litebox_broker_platform_linux_userland", version = "0.1.0" }
litebox_broker_transport_linux_userland = { path = "../litebox_broker_transport_linux_userland", version = "0.1.0" }
litebox_syscall_rewriter = { path = "../litebox_syscall_rewriter", version = "0.1.0" }
tempfile = { version = "3", default-features = false }

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
litebox_broker_transport_windows_userland = { path = "../litebox_broker_transport_windows_userland", version = "0.1.0" }
windows-sys = { version = "0.60.2", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }

[features]
lock_tracing = [
    "litebox_platform/lock_tracing",
    "litebox_broker_platform_linux_userland/lock_tracing",
]

[[bin]]
name = "litebox-broker-userland"
path = "src/main.rs"

[[test]]
name = "userland_broker"
path = "tests/userland_broker.rs"
harness = false

[dev-dependencies]
litebox_broker_local = { path = "../litebox_broker_local", version = "0.1.0" }

[lints]
workspace = true
