[package]
name = "litebox_broker_platform_linux_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { version = "0.2.177", default-features = false }
litebox_broker_core = { path = "../litebox_broker_core", version = "0.1.0" }
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }
rustix = { version = "1.1.2", default-features = false, features = ["event", "net", "std"] }

[lints]
workspace = true
