[package]
name = "litebox_broker_platform_linux_userland"
version = "0.1.0"
edition = "2024"

[dependencies]
litebox_broker_core = { path = "../litebox_broker_core", version = "0.1.0" }
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }
litebox_platform = { path = "../litebox_platform", version = "0.1.0" }
rustix = { version = "1.1.2", default-features = false, features = ["event", "net", "std", "thread"] }

[features]
lock_tracing = ["litebox_platform/lock_tracing"]

[lints]
workspace = true
