[package]
name = "litebox_broker_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.9.0", default-features = false }
hashbrown = "0.15.2"
litebox_broker_protocol = { path = "../litebox_broker_protocol", version = "0.1.0" }
spin = { version = "0.9.8", default-features = false, features = ["rwlock"] }
thiserror = { version = "2.0.6", default-features = false }

[lints]
workspace = true
